### PR TITLE
All sites: Fixes broken  views

### LINKED ISSUE #373: some slightly broken views on .com and .org sites
banner-secondary on jquery.com, jqueryui.com, jquerymobile.com, jquery.org are broken at some browser window widths, see pictures below: 

view1

view2

view3

view4

See without the bookmarklet that was hiding the problem on the right hand-side. Notice also how the download picture comes over the text.

view4-2

view5

All seems ok from this width:
view6-now-ok

view7

Also, there are inconsistencies there as well, e.g. banner-secondary div on jquery.com has class row while others don't etc. I think it'd be good to clean this if we can...

### PR DESCRIPTION
**Pull request by sigorilla**
Hi everyone!

I fixed #373 for all window widths. Also I made very big refactoring for CSS and views:

* Fix banners on plugins (ref: jquery/jquery.org#118) and events page
* CSS color from uppercase to lowercase
* Indention: tab, size: 4
* Delete `px` from zero values
* Delete unnecessary properties
* Trim all lines
* Add space after colon in CSS properties

### CODE REVIEW

**Comment by scottgonzalez** [comment]
I've done a first pass over the changes and they look good to me. Still need to do a review of the actual rendering.

**Comment by kswedberg** [comment]
Looks good to me, too. Checked the rendering with a bunch of sites locally. 
@scottgonzalez unless you have any objections, I'm going to merge this in.

**Comment by scottgonzalez** [comment]
Go for it. I've got no objections.

**Comment by kswedberg** [comment]
Closed by dace04168c49a64a36a03643eb7912863ebec076. 
Thanks, @sigorilla!

**Pull request closed without merging**
