### PR TITLE
Build: Add genesis script that will clone build and deploy all websites

### PR DESCRIPTION
**Pull request by arschmitz**
Mostly just doing this pr to see if there is interest in this i have used it myself for quite a while. If there is interest, i will add documentation on usage to the readme. 

This will setup / update every jquery-wp-content site at once. If a site
already exists it will git reset --hard origin/master, remove the node_modules
directory, npm install, and deploy the site. If the site does not exist it will
clone it, npm install, and deploy.

### CODE REVIEW

**Comment by scottgonzalez** [comment]
Who is the intended audience of such a script?

**Comment by arschmitz** [comment]
Mostly team members. Though anyone who wishes to contribute to multiple websites and does not want to clone them individually and setup individually. I did this at the request of @agcolom i mentioned that i had it earlier and she wanted to bring up in content meeting today.

**Comment by arthurvr** [comment]
I have an equivalent shell script in my dotfiles. I actually created it for https://github.com/jquery/jquery-wp-content/pull/332, I needed to test something on all sites. Turns out it's handy.

**Comment by arthurvr** [comment]
That being said, I'm not sure it's something that should live in this repo.

**Comment by scottgonzalez** [comment]
To me it just seems like another thing to maintain that provides very little value. How many people are really working on every site? How much work is it really to do a one time setup? Why are these people not just using vagrant?

**Comment by arschmitz** [comment]
how does vagrant help here these deploy to our vagrant box?

**Comment by arthurvr** [comment]
@jquery/content Where are we with this? After the meeting we said we were going to discuss this further in the ticket, do we have any consensus?

**Comment by arschmitz** [comment]
Closing this since no one ever responded

**Pull request closed without merging**
