### PR TITLE
Added jQuery Gems to footer of jQuery.com website

### PR DESCRIPTION
**Pull request by javascriptteacher**
I am the author of jQuery Gems.

Over the years, it has gained reputation as a useful jQuery Reference book.

Would it be possible to include it here?

In addition it would also need the cover image file "jquery-gems.jpg" at following location:

<?php echo get_template_directory_uri(); ?>/content/books/jquery-gems.jpg

### CODE REVIEW

**Comment by mgol** [comment]
cc @kborchers

**Comment by kborchers** [comment]
Traditionally these books have been listed because the publisher would pay royalties to the JS Foundation (or jQuery Foundation back when we started listing books on the sites) if sales came through those links. That said, to my knowledge we have rarely if ever actually received royalties because the publisher has a per book minimum royalty you have to earn for them to pay out.

All of that was the long way of saying, I'm fine with swapping in new books if:
1. The project team that owns the site agrees that the book is a good resource for your users
2. The project team owns these updates as I do not have the bandwidth to maintain them

**Comment by mgol** [comment]
@kborchers I see. The content team seriously lacks manpower recently so it's hard to say there's anyone available to maintain those lists.

What do you think, @dmethvin @AurelioDeRosa?

**Comment by AurelioDeRosa** [comment]
I'm OK in maintaining the list, however that would not be high on my priority list.

**Comment by dmethvin** [comment]
Besides the publishers having donated to the JSF, the authors of the existing books (such as @AurelioDeRosa 😸) have been or currently are contributors to one or more projects. That seems like a good non-arbitrary way to limit the list since there are a LOT of jQuery books out there.

**Comment by jorydotcom** [comment]
as this PR has been open 3+ years, the contributor has not signed the CLA, and the book does not meet the rough guidelines provided by @dmethvin or @kborchers, it seems the issue should be closed. Please re-open if there should be further discussion or conversation.

**Pull request closed without merging**
