### PR TITLE
Add herodevs support.

### PR DESCRIPTION
**Pull request by AndreAngelantoni**
This support https://github.com/jquery/jquery-wp-content/issues/462.

Within this find:
1. add status message top of screen on homepage
2. add Support menu item to navigation bar
3. add warning box to API pages
4. add styling for the above

Please note: I'm unable to confirm that #3 is in the correct theme file as we could not get the API site to work locally (two devs, two different machines). The guidelines indicate that making this guess may be acceptable.

### CODE REVIEW

**Comment by mgol** [comment]
You'll need to sign our CLA. Follow the link from the EasyCLA bot.

**Comment by AndreAngelantoni** [comment]
@mgol thanks! Shortly after submitting, Joe and I did the paperwork. We should be good to go.

Also, I'm off-grid for the next nine days. Still would be great to move this forward will I'm gone if it's easy to do so. Joe can answer questions about why I did certain things (and we aren't attached to the details).

**Comment by mgol** [comment]
The EasyCLA check is still red. Can you make sure the process is followed? The EasyCLA bot provided a link above.

**Comment by mgol** [comment]
The EasyCLA check is still red. Can you make sure the process is followed? The EasyCLA bot provided a link above. Unfortunately, that's a blocker with following up on this.

**Comment by joeeames** [comment]
ok, i just submitted a ticket. I thought I already did this...sorry

**Comment by AndreAngelantoni** [comment]
@joeeames @mgol I thought I had signed correctly last time but I did it again just now as a corporate contributor. For good measure, I signed it individually just now (and use my andre@herodevs.com email address).

Michael, how do you recommend we proceed? The Not Covered badge is still present yet I believe I've done what's needed.

**Comment by AndreAngelantoni** [comment]
I think I figured out what's happening. The commits came in under my personal account. @joeeames I've sent a request to you but this time it will come from aangelinsf. Please approve and we should be good to go.

**Comment by mgol** [comment]
@AndreAngelantoni you can squash the commits into one and amend the author info, doing a `git push --force-with-lease` afterwards; then the check will pass.

**Comment by AndreAngelantoni** [comment]
Thanks, Michał. Timmy wants to work with me now that I'm back from vacation
so the commits may yet change.

**Comment by AndreAngelantoni** [comment]
Closing in favor of https://github.com/jquery/jquery-wp-content/pull/467.

**Pull request closed without merging**
