### PR TITLE
jquery: show the Qunit logo

### LINKED ISSUE #434: QUnit logo is not showing on the homepage
It misses the CSS to show QUnit logo. A few lines of CSS can fix it can I can make a pull request.
jquery

### PR DESCRIPTION
**Pull request by tomoyanime**
This PR fixes #434

### CODE REVIEW

**Comment by mgol** [comment]
Thanks for the PR. We need you to sign the CLA before we can accept it.

**Comment by tomoyanime** [comment]
@mgol  I signed it.

**Review by mgol — APPROVED** [review]
Thank you!

**Comment by tomoyanime** [comment]
You're welcome!

**Pull request merged**
