### PR TITLE
Fix some responsiveness issues.

### PR DESCRIPTION
**Pull request by 10by10pixel**

### CODE REVIEW

**Comment by arthurvr** [comment]
And what issue does this fix exactly? Screenshots would be awesome but at least try to explain what you're trying to fix :)

**Comment by 10by10pixel** [comment]
There are some things off the page and mismatching sizes that don't look good.

**Comment by arthurvr** [comment]
> There are some things off the page and mismatching sizes that don't look good.

Could you be a little more specific? What site are you talking about? What page? Which sizes exactly?

**Comment by 10by10pixel** [comment]
See the page width was 700px but CSS wasn't set to change until 600px.

**Comment by 10by10pixel** [comment]
screenshot 2015-05-24 at 3 35 23 pm
Here's an example of some graphics errors seen on the frontpage with a 700px screen.

**Comment by arthurvr** [comment]
Thanks. Now I understand what the problem is. Thanks! We should definitely take care of that. Though It looks like this causes other problems:

jquery_api_documentation

**Comment by arthurvr** [comment]
Friendly ping @10by10pixel

**Comment by 10by10pixel** [comment]
I'm sure things could be adjusted. I just adjusted a couple lines of css.

**Comment by 10by10pixel** [comment]
What exactly is the issue on that picture? Is it that image on the side?

**Comment by arthurvr** [comment]
Yes.

**Comment by 10by10pixel** [comment]
Maybe make it go on it's own line like it does in the mobile layout?

**Comment by 10by10pixel** [comment]
@arthurvr Checking in on my old open PRs Whatever happened to this?

**Comment by mgol** [comment]
@10by10pixel I was about to land it (sorry, we seriously lack manpower in this project) but our CLA has changed to the JS Foundation one and we're required to ask contributors to sign the new one. :/ Could you do that? I promise to land it shortly afterwards (just ping me that you've done it afterwards).

**Comment by 10by10pixel** [comment]
@mgol Done

**Comment by mgol** [comment]
Thanks!

**Pull request merged**
