### PR TITLE
api.jqueryui.com: Prepare for jQuery UI 1.14

### PR DESCRIPTION
**Pull request by mgol**
Also, update jQuery UI used on releases.jquery.com from 1.13.2 to 1.13.3.

### CODE REVIEW

**Comment by mgol** [comment]
@Krinkle Also, could you edit the jQuery UI Wiki to update the instructions for the new infra? I think only the section at https://github.com/jquery/jquery-ui/wiki/Release-process#apijqueryuicom is affected; it mentions `builder.pp` & the `puppet-stage` branch.

**Comment by mgol** [comment]
@Krinkle This may be a stretch with the current activity, but what if I wanted to start working on a site for the next UI release (here: `1.14`) while not tagging it as the default version? I could create an entry for `api_jqueryui_com_1_14` and after `1.14.0` final rename the existing `api_jqueryui_com` to `api_jqueryui_com_1_13` followed by the renaming of `api_jqueryui_com_1_14` to `api_jqueryui_com`; would that work?

**Comment by Krinkle** [comment]
@mgol I believe so, yes. I don't think we have any coupling to, or awareness of, what the subsites represent, at the infrastructure level. So a subsite being "semver newer" than the main site, should not pose an problem.

We shall find out on staging, but from reviewing the code just now, I don't see anything stand out that would go wrong.

I do note that if we do this, the 1.14 subsite would become 404 Not Found, although we can fix that by adding a 302 redirect for it under the `api_jqueryui_com` block in `infrastructure-puppet:/hierdata/common.yaml` (I suggest 302, since it may potentially become a directory again in the future.)

**Comment by mgol** [comment]
OK, I guess I'll just switch the docs to 1.14 at this point to reduce the churn a bit. API changes are minor so the docs should work just as fine for 1.13 users.

**Comment by mgol** [comment]
@Krinkle do those changes in instructions look good to you? https://github.com/jquery/jquery-ui/wiki/Release-process/_compare/fc525d9ce775de628e1fa4df6de48154b8b6dff3...50e53262fdfae7363f92886f212fb6c8752dee59

**Comment by mgol** [comment]
A counterpart infra PR: https://github.com/jquery/infrastructure-puppet/pull/56

**Pull request merged**
