### PR TITLE
All: Add Algolia's DocSearch to UI/Mobile/QUnit website searches

### PR DESCRIPTION
**Pull request by s-pace**
This PR will add DocSearch to all other documentation websites as https://jquery.com/. It will allow an user to have a learn-as-you-type experience by displaying results thanks to a dropdown in a live way.

If there is no result, pressing enter will enable the legacy search.

Follow #416

### CODE REVIEW

**Comment by s-pace** [comment]
Sorry for the ping here but I am sure @mgol will be glad to hit that button.

Hope you are doing well by the way! Send us an email to docsearch@algolia.com, we have some swags for you :)

**Comment by s-pace** [comment]
May be @ dmethvin will be also happy to hit the green button. Same, feel free to reach out to us by email :)

**Comment by mgol** [comment]
Thanks for the PR, @s-pace! I remember about it, I just want to test it locally first.

Also, we've got a bug report at https://github.com/jquery/codeorigin.jquery.com/issues/49 that our copy to clipboard button is now broken; @dmethvin suggested there might be a problem with the Algolia code. I'd like to double check it before merging as well, unless you're able to verify quickly whether the issue is related or not.

**Comment by s-pace** [comment]
Should be good now @mgol

**Comment by mgol** [comment]
Thanks! I'll try to merge it in within the next few days.

**Comment by mgol** [comment]
@leobalter @trentmwillis @arschmitz Are you OK with this change? This will introduce an autocomplete-based search on UI/Mobile/QUnit pages similar to one that we already have on https://jquery.com/ & https://api.jquery.com/

**Comment by trentmwillis** [comment]
@mgol seems fine for QUnit (though some of the QUnit docs have moved to GitHub pages and won't be included)

**Comment by mgol** [comment]
Landed, thanks!

**Pull request merged**
