### PR TITLE
Styles for figure/figcaption on api.jquery.com

### PR DESCRIPTION
**Pull request by kswedberg**
These styles are in preparation for a commit on api.jquery.com (see https://github.com/jquery/api.jquery.com/issues/829)

### CODE REVIEW

**Comment by kswedberg** [comment]
by the way, this shouldn't have any effect on the site as it is now. Will only affect new markup introduced in commit noted above.

**Comment by scottgonzalez** [comment]
I guess this is good, though we should probably wait for at least one entry to be updated to actually use a figure element.

**Comment by kswedberg** [comment]
They're already there on staging. e.g. http://stage.api.jquery.com/click/

**Comment by scottgonzalez** [comment]
Oh, in that case, let's merge!

**Comment by scottgonzalez** [comment]
Live on staging and production now.

**Comment by kswedberg** [comment]
thanks, @scottgonzalez !

**Pull request closed without merging**
