### PR TITLE
jquerymobile.com: Add books to footer

### PR DESCRIPTION
**Pull request by kborchers**

### CODE REVIEW

**Comment by kborchers** [comment]
@arschmitz Can you please review and merge if you are happy with this?

**Comment by kborchers** [comment]
Can someone from @jquery/mobile and/or @jquery/content review and merge this so they stop bothering me? I just want another set of eyes to ok it before changing the template for this site.

**Comment by jaspermdegroot** [comment]
@kborchers 

I just reviewed and everything looks good. I don't have write access to this repo so I can't merge for you.

Because I am sure other authors that have their book listed on our Resources page are going to ask us how to get their book in the footer ... is this part of a sponsorship deal?

**Comment by kborchers** [comment]
There is no specific sponsorship deal but we do get royalties on jQuery related books. They sent me these new books and I just noticed that there were no books in the footer of this site. We can just add them to the resources page if that works better for this site though they are not all mobile related.

**Comment by arschmitz** [comment]
I think i like the idea of having some in the footer for consistency with other sites. I am thinking we should just do the 3 newest ones in the footer. If any one asks how to get in the footer there is a simple answer. It also makes sense to feature the 3 most up to date books i think.

**Comment by arthurvr** [comment]
> I am thinking we should just do the 3 newest ones in the footer. If any one asks how to get in the footer there is a simple answer. It also makes sense to feature the 3 most up to date books i think.

Yeah, I agree. In fact it would be even better if we could actually review the books and choose the *best* one, not the newest one, but I guess that's not possible.

**Comment by arschmitz** [comment]
@arthurvr "best" is always going to be a judgement call and its the kind of judgement i don't think we want to get into. We don't want to alienate authors. We are not book critics and as a foundation or a project i don't think we want to be. These are all published books /authors. I think its fair to assume they are all good.

**Comment by kborchers** [comment]
Agree 100% with @arschmitz

**Comment by jaspermdegroot** [comment]
Although it would be nice to have the latest books in the footer, it would mean that we have to do two PRs for each book that we add and I also think no one on the Mobile team has the rights to merge the PR in the jquery-wp-content repo. So I think it's better if we use more static content for templates that are in this repo.

**Comment by arschmitz** [comment]
@jaspermdegroot Both @agcolom , myself and the content team all have access and any one on the mobile team can do a PR I don't think this is an issue.

**Comment by scottgonzalez** [comment]
> Although it would be nice to have the latest books in the footer, it would mean that we have to do two PRs for each book that we add

Or we can just automate it from some structured data so that adding a new book is just a matter of adding another item to an array.

**Comment by arthurvr** [comment]
> Or we can just automate it from some structured data so that adding a new book is just a matter of adding another item to an array.

:+1:

**Comment by gregsidelnikov** [comment]
Would anyone be interested adding jQuery Gems to refresh the footer? Please contact me.

**Pull request closed without merging**
