### PR TITLE
jquery: Update jQuery from 1.11.2 to 1.11.3

### PR DESCRIPTION
**Pull request by mzgol**

### CODE REVIEW

**Comment by mzgol** [comment]
This is simple so I'd like to land it soon. @jquery/content, any objections? Are there other places I'd need to check?

**Comment by arthurvr** [comment]
> any objections? Are there other places I'd need to check?

Looks good to me at least. :+1: We didn't have to update anything else in https://github.com/jquery/jquery-wp-content/pull/332 as well.

**Comment by mzgol** [comment]
I see the branch name I created looks misleading. ;) I did upgrade to 1.11.3 as there is no 1.11.4.

Should I test anything in particular before landing this?

**Comment by jzaefferer** [comment]
Can we use our own CDN instead of maintaining a copy in this repository? Seems like a good opportunity to fix that.

**Comment by mzgol** [comment]
We *are* using the CDN, look closer at the diff. The local copy is to be
able to run the page locally offline (the document.write hack is used to do
that).

-- 
Michał Gołębiowski

**Comment by mzgol** [comment]
We're using the Google CDN instead of our own, though.

-- 
Michał Gołębiowski

**Comment by jzaefferer** [comment]
Sorry, I ignored the diff. Let's replace the whole thing with only using the jQuery CDN. We fully rely on that elsewhere anyway.

**Comment by mzgol** [comment]
Where do we rely on it?

-- 
Michał Gołębiowski

**Comment by scottgonzalez** [comment]
Every single demo on the API sites.

**Comment by mzgol** [comment]
OK, fair enough. That reminds me API sites need their jQueries updated as well, e.g. https://github.com/jquery/api.jquery.com/blob/320265a67851969e02837b88f14802d93ef8e7fc/entries2html.xsl specifies 1.10.2.

**Comment by arthurvr** [comment]
> OK, fair enough. That reminds me API sites need their jQueries updated as well, e.g. https://github.com/jquery/api.jquery.com/blob/320265a67851969e02837b88f14802d93ef8e7fc/entries2html.xsl specifies 1.10.2.

Yep, there's an open issue about that. I was planning to wait till the v3 release.

**Comment by mzgol** [comment]
> Yep, there's an open issue about that. I was planning to wait till the v3 release.

We'll have 1.12.0 & 2.2.0 shortly before 3.0.0; seems fine to just wait until 3.0.0 then as it will require making sure API examples wouldn't break.

**Comment by mzgol** [comment]
PR updated. I used the https link, although previously there was a relative-protocol one. I also see a lot of links are hardcoded to http... That's bad.

What's stopping us from switching all protocol-relative links to https? Why do we still need to even make the site available over http? Is there an issue I could track?

**Comment by arthurvr** [comment]
> seems fine to just wait until 3.0.0 then as it will require making sure API examples wouldn't break.

:+1: 

> What's stopping us from switching all protocol-relative links to https? Why do we still need to even make the site available over http? Is there an issue I could track?

Yeah, we've been discussing this in the content meetings but one of us will need to go through all sites to remove those links that are hardcoded to `http` first. I was planning to  do this but haven't had much time lately. It's on my todo list though, I should have time for it soon.

**Comment by mzgol** [comment]
OK, in any case, this PR should be good. Can I get some LGTMs?

**Comment by jzaefferer** [comment]
You're still adding `themes/jquery/js/jquery-1.11.3.min.js` - don't need that anymore, right?

**Comment by mzgol** [comment]
Right, sorry, fixed.

**Comment by jzaefferer** [comment]
Looks good.

**Pull request merged**
