### PR TITLE
irc.jquery.org: Add new IRC log channels

### PR DESCRIPTION
**Pull request by ryanneufeld**
Add new IRC channels.
Sort list alphabetically.

fixes jquery/irc.jquery.org#15

### CODE REVIEW

**Comment by arthurvr** [comment]
These should be added to https://github.com/jquery/irc.jquery.org/blob/master/pages/index.html#L17 too.

**Comment by scottgonzalez** [comment]
@ryanneufeld I had to change your email address to match your CAA signature. Please update your git config.

**Comment by ryanneufeld** [comment]
Sorry. Was on work computer. Should I sign with my work address as well?
Would that make it easier?

**Comment by scottgonzalez** [comment]
That's up to you, whether you want contributions to be going through your work address.

**Comment by ryanneufeld** [comment]
Okay. Thanks for fixing that for me.

--Ryan Neufeld BSc CIS
ryan@neufeldmail.com

**Pull request closed without merging**
