### PR TITLE
jqueryui.com: Increase height for demo frame to compensate font-size++

### PR DESCRIPTION
**Pull request by jzaefferer**
Ref jquery/jqueryui.com#110

### CODE REVIEW

**Comment by scottgonzalez** [comment]
I assume we'll wait for the release before we do this.

**Comment by jzaefferer** [comment]
Yeah, though at least this one wouldn't break anything.

**Comment by mgol** [comment]
@jzaefferer is it OK to land it now?

**Comment by jzaefferer** [comment]
Sure

**Pull request merged**
