### PR TITLE
Update header.php

### PR DESCRIPTION
**Pull request by coliff**
Update jQuery to 1.12.0 - and switched to minified version for faster loading

### CODE REVIEW

**Comment by AurelioDeRosa** [comment]
LGTM. Can I merge?

**Comment by dmethvin** [comment]
Was any testing done on this? I know we have at least one issue related to UI that might break the UI docs pages. Probably better to wait for the `.1` release unless @coliff has tested this pretty thoroughly.

**Comment by dmethvin** [comment]
Oh but we aren't using Migrate on our setup, so that bug shouldn't apply. My concern about testing is still there.

**Comment by mgol** [comment]
@dmethvin I think at this point we'd like to update it all to jQuery 3 if possible so I'll close this issue. It's not worth it to test the site on 1.12 which is already outdated. Sorry @coliff

**Pull request closed without merging**
