### PR TITLE
jquery.com issue#70 logos center-aligned for phone

### PR DESCRIPTION
**Pull request by ashg1910**
corresponding to:
https://github.com/jquery/jquery.com/issues/70

### CODE REVIEW

**Comment by arthurvr** [comment]
I like it better but IMHO this big logos are a little annoying on mobile. Anyways I'm fine with landing it, it's definitely an improvement, what does the rest think?

**Comment by arthurvr** [comment]
> I like it better but IMHO this big logos are a little annoying on mobile. Anyways I'm fine with landing this, it does actually look better.

What does the rest think?

**Comment by AurelioDeRosa** [comment]
I'm fine with the PR.

**Comment by arthurvr** [comment]
Thanks @ashg1910.

**Pull request closed without merging**
