### PR TITLE
contribute.jquery.org: Sanitize input before rendering as HTML

### PR DESCRIPTION
**Pull request by gibson042**
cf. http://contribute.jquery.org/CLA/status/?owner=jquery&repo=jquery&sha=e217c1949f625c4c4ae7b9e93943310c73ef55ac

### CODE REVIEW

**Comment by mgol** [comment]
The link no longer works.

**Comment by gibson042** [comment]
Well, I suppose the consequences of submitting commit hashes containing single-quote characters (or worse) without this change are obvious.

**Comment by mgol** [comment]
Yeah, that's true.

**Comment by mgol** [comment]
This may only bite in combination with CLA checker bugs, right? User-provided input was already sanitized, repo/owner/sha are first used to generate `$data` and nothing would be found for rogue fake ones.

**Comment by gibson042** [comment]
I believe that's correct.

**Comment by mgol** [comment]
OK, it shouldn't be extremely critical then. LGTM.

**Comment by gibson042** [comment]
A year and a half with no injection attacks, but I updated it anyway. :upside_down_face:

**Pull request merged**
