### PR TITLE
All: upgrade relevanssi plugin

### PR DESCRIPTION
**Pull request by timmywil**
I hit an error when attempting to run `grunt deploy` on some sites. WPLANG wasn't always defined. Fortunately, the error was fixed upstream.

I've upgraded the plugin to it's latest 3.x version. 4.x may work fine, but I didn't want to deal with breaking changes just yet. It does note a requirement of PHP 5.6, but I realized I've been running all sites on php version 8.2.7. I think we could upgrade all machines to at least 5.6. If that's not the case, there's also the possibility that the php 5.6 requirement set by relevanssi may not indicate earlier versions would have problems because before that they had not set a php requirement at all.

### CODE REVIEW

**Review by mgol — APPROVED** [review]

**Review by mgol — APPROVED** [review]
The change is probably fine but is this our code or vendor one? If vendor one then it's best to avoid modifying this unless we confirm the latest version doesn't have this issue. Otherwise, we can bring some issues back just by upgrading dependencies.

Also, if this is a vendor file, it'd be good to add a marker comment for our modification - and maybe leave the code commented out to see the original.

**Comment by timmywil** [comment]
Now that you say that, I'm not sure. I thought we wrote all the plugins.

**Comment by Krinkle** [comment]
* https://wordpress.org/plugins/relevanssi/
* https://github.com/msaari/relevanssi
* https://github.com/msaari/relevanssi/blob/3.5.9/lib/stopwords.php

**Comment by timmywil** [comment]
Thanks, it seems this has been fixed upstream through the use of a `defined` check.

**Comment by timmywil** [comment]
Is there a reason you linked 3.5.9? I understand not wanting to do a major version upgrade to latest (4.20.0), but the latest 3.x is 3.6.2 (or possibly "3.6.2.2")

**Comment by Krinkle** [comment]
I linked `3.5.9` as being the closest to the version we currently have. We wanted to link to relevanssi 3.3.8, which is what we have (per readme.txt), but that version isn't present in the canonical upstream repo. 3.5.9 is the oldest/closest I found.

I agree that in terms of upgrade, I suggest moving to the latest 3.x first.

The full 3.x changelog is available at <https://github.com/msaari/relevanssi/blob/3.6.2.2/readme.txt#L270-L420>. Note that the old servers currently run WordPress 4.5.2 and PHP 5.4.

**Comment by timmywil** [comment]
It looks like the php requirement wasn't set at all until version 3.6. PHP 5.6 may be an arbitrary restriction.

**Comment by Krinkle** [comment]
Re-opening to trigger the new PHP 5.4 lint job, just in case :)

**Comment by Krinkle** [comment]
I updated the commit message to explicitly reference the source zip URL, and confirmed that `rm -rf relevanssi`; `curl … | tar -xz -z`; `mv relevanssi-* relevanssi` leaves no difference with this patch.

Merged in https://github.com/jquery/jquery-wp-content/commit/78880cdac26d14ba0215722fdea8d529a2b46dd3.

**Pull request closed without merging**
